#!/bin/perl

use Module::CoreList;
use List::Util qw(max);

my @modules = sort keys $Module::CoreList::version{5.014002};

my $max_length = max map {length} @modules;

foreach (@modules) {
    printf "%*s %s\n", -$max_length, $_, Module::CoreList -> first_release( $_ );
}
